site_name: Swarm External Secrets

theme:
  name: material

docs_dir: docs

nav:
  - Home: index.md
  - Debug Plugin: DEBUG_PLUGIN.md
  - Monitoring: MONITORING.md
  - Multi Provider: MULTI_PROVIDER.md
  - Rotation: ROTATION.md
