name: lefthook pre validate

on: [push, pull_request]

permissions: read-all

jobs:
  lefthook:
    name: lefthook
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.1.0
        with:
          go-version: '1.24.2'
          cache: true


      - name: Install lefthook and linters
        run: |
          go install github.com/evilmartians/lefthook@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
          go install golang.org/x/tools/cmd/goimports@latest

      - name: Run lefthook pre-commit hooks
        run: lefthook run pre-commit --all-files 

      - name: Check for uncommitted changes
        run: git diff --exit-code
